server:
  port: 8182
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.82.36:18848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql
    url: jdbc:mysql://124.223.82.36:18888/seat-account
    username: root

logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml

#====================================Seata Config===============================================
seata:
  tx-service-group: seata-account-group
  registry:
    type: nacos
    nacos:
      server-addr: 124.223.82.36:18848
      application: seata-server
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 124.223.82.36:18848
      group: SEATA_GROUP
      dataId: "seataServer.properties"